// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xmrkvemxjyvhfmneymam.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhtcmt2ZW14anl2aGZtbmV5bWFtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1OTUzNDUsImV4cCI6MjA3MTE3MTM0NX0.QX1h4dNJoHXvGN5RWU5sdUIC1ouIbgzxH2lneywvYtM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});